from crewai import Task
from core.research_processor import process_ticket_research
from agents.research_agent import research_agent

def create_research_task(ticket_text: str) -> Task:
   
    research_output = process_ticket_research(ticket_text)

    return Task(
        description="Structured KB matches for each issue part, auto-generated by processor.",
        expected_output="Precomputed research output (used as context by support agent).",
        agent=research_agent,
        output=research_output
    )

